//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Strings.resx by eng/UpdateStrings.cs. Do not edit by hand:
//     change the resx and run "dotnet run eng/UpdateStrings.cs".
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace WinClean.Resources;

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("eng/UpdateStrings.cs", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.Runtime.CompilerServices.CompilerGenerated]
public static class Strings
{
    private static ResourceManager? resourceManager;

    public static ResourceManager ResourceManager =>
        resourceManager ??= new ResourceManager("WinClean.Resources.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    /// <summary>"WinClean"</summary>
    public static string AppName => ResourceManager.GetString("AppName", Culture)!;

    /// <summary>"Cancel"</summary>
    public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", Culture)!;

    /// <summary>"Close"</summary>
    public static string Common_Close => ResourceManager.GetString("Common_Close", Culture)!;

    /// <summary>"Copy"</summary>
    public static string Common_Copy => ResourceManager.GetString("Common_Copy", Culture)!;

    /// <summary>"Copy path"</summary>
    public static string Common_CopyPath => ResourceManager.GetString("Common_CopyPath", Culture)!;

    /// <summary>"Open file location"</summary>
    public static string Common_OpenLocation => ResourceManager.GetString("Common_OpenLocation", Culture)!;

    /// <summary>"Refresh"</summary>
    public static string Common_Refresh => ResourceManager.GetString("Common_Refresh", Culture)!;

    /// <summary>"Cleanup"</summary>
    public static string Nav_Cleanup => ResourceManager.GetString("Nav_Cleanup", Culture)!;

    /// <summary>"Collapse navigation"</summary>
    public static string Nav_Collapse => ResourceManager.GetString("Nav_Collapse", Culture)!;

    /// <summary>"Expand navigation"</summary>
    public static string Nav_Expand => ResourceManager.GetString("Nav_Expand", Culture)!;

    /// <summary>"Hardware"</summary>
    public static string Nav_Hardware => ResourceManager.GetString("Nav_Hardware", Culture)!;

    /// <summary>"Health"</summary>
    public static string Nav_Health => ResourceManager.GetString("Nav_Health", Culture)!;

    /// <summary>"Overview"</summary>
    public static string Nav_Overview => ResourceManager.GetString("Nav_Overview", Culture)!;

    /// <summary>"Processes"</summary>
    public static string Nav_Processes => ResourceManager.GetString("Nav_Processes", Culture)!;

    /// <summary>"Settings"</summary>
    public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", Culture)!;

    /// <summary>"Storage"</summary>
    public static string Nav_Storage => ResourceManager.GetString("Nav_Storage", Culture)!;

    /// <summary>"Not available" (Shown wherever a value cannot be read on this machine.)</summary>
    public static string NotAvailable => ResourceManager.GetString("NotAvailable", Culture)!;

    /// <summary>"Nothing to show yet." (Placeholder while a page has no data.)</summary>
    public static string Page_NothingYet => ResourceManager.GetString("Page_NothingYet", Culture)!;
}
