//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from Strings.resx by eng/UpdateStrings.cs. Do not edit by hand:
//     change the resx and run "dotnet run eng/UpdateStrings.cs".
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace WinClean.Resources;

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("eng/UpdateStrings.cs", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.Runtime.CompilerServices.CompilerGenerated]
public static class Strings
{
    private static ResourceManager? resourceManager;

    public static ResourceManager ResourceManager =>
        resourceManager ??= new ResourceManager("WinClean.Resources.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    /// <summary>"WinClean"</summary>
    public static string AppName => ResourceManager.GetString("AppName", Culture)!;

    /// <summary>"Coding agent"</summary>
    public static string Category_AiAgent => ResourceManager.GetString("Category_AiAgent", Culture)!;

    /// <summary>"Browser"</summary>
    public static string Category_Browser => ResourceManager.GetString("Category_Browser", Culture)!;

    /// <summary>"Containers"</summary>
    public static string Category_Container => ResourceManager.GetString("Category_Container", Culture)!;

    /// <summary>"Editor"</summary>
    public static string Category_Editor => ResourceManager.GetString("Category_Editor", Culture)!;

    /// <summary>"IDE"</summary>
    public static string Category_Ide => ResourceManager.GetString("Category_Ide", Culture)!;

    /// <summary>"Package manager"</summary>
    public static string Category_PackageManager => ResourceManager.GetString("Category_PackageManager", Culture)!;

    /// <summary>"Runtime"</summary>
    public static string Category_Runtime => ResourceManager.GetString("Category_Runtime", Culture)!;

    /// <summary>"Shell"</summary>
    public static string Category_Shell => ResourceManager.GetString("Category_Shell", Culture)!;

    /// <summary>"Terminal"</summary>
    public static string Category_Terminal => ResourceManager.GetString("Category_Terminal", Culture)!;

    /// <summary>"Version control"</summary>
    public static string Category_VersionControl => ResourceManager.GetString("Category_VersionControl", Culture)!;

    /// <summary>"Virtual machine"</summary>
    public static string Category_VirtualMachine => ResourceManager.GetString("Category_VirtualMachine", Culture)!;

    /// <summary>"Windows"</summary>
    public static string Category_Windows => ResourceManager.GetString("Category_Windows", Culture)!;

    /// <summary>"Cancel"</summary>
    public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", Culture)!;

    /// <summary>"Clear"</summary>
    public static string Common_Clear => ResourceManager.GetString("Common_Clear", Culture)!;

    /// <summary>"Close"</summary>
    public static string Common_Close => ResourceManager.GetString("Common_Close", Culture)!;

    /// <summary>"Copy"</summary>
    public static string Common_Copy => ResourceManager.GetString("Common_Copy", Culture)!;

    /// <summary>"Copy path"</summary>
    public static string Common_CopyPath => ResourceManager.GetString("Common_CopyPath", Culture)!;

    /// <summary>"Dismiss"</summary>
    public static string Common_Dismiss => ResourceManager.GetString("Common_Dismiss", Culture)!;

    /// <summary>"Open file location"</summary>
    public static string Common_OpenLocation => ResourceManager.GetString("Common_OpenLocation", Culture)!;

    /// <summary>"Properties"</summary>
    public static string Common_Properties => ResourceManager.GetString("Common_Properties", Culture)!;

    /// <summary>"Refresh"</summary>
    public static string Common_Refresh => ResourceManager.GetString("Common_Refresh", Culture)!;

    /// <summary>"Not available (access denied)"</summary>
    public static string Details_AccessDenied => ResourceManager.GetString("Details_AccessDenied", Culture)!;

    /// <summary>"Architecture"</summary>
    public static string Details_Architecture => ResourceManager.GetString("Details_Architecture", Culture)!;

    /// <summary>"Command line"</summary>
    public static string Details_CommandLine => ResourceManager.GetString("Details_CommandLine", Culture)!;

    /// <summary>"Commit"</summary>
    public static string Details_Commit => ResourceManager.GetString("Details_Commit", Culture)!;

    /// <summary>"CPU time"</summary>
    public static string Details_CpuTime => ResourceManager.GetString("Details_CpuTime", Culture)!;

    /// <summary>"Elevated"</summary>
    public static string Details_Elevated => ResourceManager.GetString("Details_Elevated", Culture)!;

    /// <summary>"GPU memory"</summary>
    public static string Details_GpuMemory => ResourceManager.GetString("Details_GpuMemory", Culture)!;

    /// <summary>"Handles"</summary>
    public static string Details_Handles => ResourceManager.GetString("Details_Handles", Culture)!;

    /// <summary>"I/O"</summary>
    public static string Details_Io => ResourceManager.GetString("Details_Io", Culture)!;

    /// <summary>"No"</summary>
    public static string Details_No => ResourceManager.GetString("Details_No", Culture)!;

    /// <summary>"Parent"</summary>
    public static string Details_Parent => ResourceManager.GetString("Details_Parent", Culture)!;

    /// <summary>"Path"</summary>
    public static string Details_Path => ResourceManager.GetString("Details_Path", Culture)!;

    /// <summary>"PID"</summary>
    public static string Details_Pid => ResourceManager.GetString("Details_Pid", Culture)!;

    /// <summary>"Private working set"</summary>
    public static string Details_PrivateWorkingSet => ResourceManager.GetString("Details_PrivateWorkingSet", Culture)!;

    /// <summary>"Session"</summary>
    public static string Details_Session => ResourceManager.GetString("Details_Session", Culture)!;

    /// <summary>"Started"</summary>
    public static string Details_Started => ResourceManager.GetString("Details_Started", Culture)!;

    /// <summary>"Threads"</summary>
    public static string Details_Threads => ResourceManager.GetString("Details_Threads", Culture)!;

    /// <summary>"User"</summary>
    public static string Details_User => ResourceManager.GetString("Details_User", Culture)!;

    /// <summary>"Windows"</summary>
    public static string Details_Windows => ResourceManager.GetString("Details_Windows", Culture)!;

    /// <summary>"Working set"</summary>
    public static string Details_WorkingSet => ResourceManager.GetString("Details_WorkingSet", Culture)!;

    /// <summary>"Yes"</summary>
    public static string Details_Yes => ResourceManager.GetString("Details_Yes", Culture)!;

    /// <summary>"Copy details"</summary>
    public static string Error_CopyDetails => ResourceManager.GetString("Error_CopyDetails", Culture)!;

    /// <summary>"WinClean ran into a problem."</summary>
    public static string Error_Heading => ResourceManager.GetString("Error_Heading", Culture)!;

    /// <summary>"The details were saved to {0}. You can keep using WinClean. If this happens again, please report it with the details attached." ({0} is the report file path.)</summary>
    public static string Error_Message => ResourceManager.GetString("Error_Message", Culture)!;

    /// <summary>"The details could not be saved to the log folder. You can keep using WinClean. If this happens again, please report it with the details below."</summary>
    public static string Error_MessageNoFile => ResourceManager.GetString("Error_MessageNoFile", Culture)!;

    /// <summary>"Open log folder"</summary>
    public static string Error_OpenLogFolder => ResourceManager.GetString("Error_OpenLogFolder", Culture)!;

    /// <summary>"Report on GitHub" (Opens the browser; the only network action here.)</summary>
    public static string Error_Report => ResourceManager.GetString("Error_Report", Culture)!;

    /// <summary>"Unexpected error"</summary>
    public static string Error_Title => ResourceManager.GetString("Error_Title", Culture)!;

    /// <summary>"Cleanup"</summary>
    public static string Nav_Cleanup => ResourceManager.GetString("Nav_Cleanup", Culture)!;

    /// <summary>"Collapse navigation"</summary>
    public static string Nav_Collapse => ResourceManager.GetString("Nav_Collapse", Culture)!;

    /// <summary>"Expand navigation"</summary>
    public static string Nav_Expand => ResourceManager.GetString("Nav_Expand", Culture)!;

    /// <summary>"Hardware"</summary>
    public static string Nav_Hardware => ResourceManager.GetString("Nav_Hardware", Culture)!;

    /// <summary>"Health"</summary>
    public static string Nav_Health => ResourceManager.GetString("Nav_Health", Culture)!;

    /// <summary>"Overview"</summary>
    public static string Nav_Overview => ResourceManager.GetString("Nav_Overview", Culture)!;

    /// <summary>"Processes"</summary>
    public static string Nav_Processes => ResourceManager.GetString("Nav_Processes", Culture)!;

    /// <summary>"Settings"</summary>
    public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", Culture)!;

    /// <summary>"Storage"</summary>
    public static string Nav_Storage => ResourceManager.GetString("Nav_Storage", Culture)!;

    /// <summary>"Not available" (Shown wherever a value cannot be read on this machine.)</summary>
    public static string NotAvailable => ResourceManager.GetString("NotAvailable", Culture)!;

    /// <summary>"Battery"</summary>
    public static string Overview_Battery => ResourceManager.GetString("Overview_Battery", Culture)!;

    /// <summary>"{0}, charging"</summary>
    public static string Overview_BatteryCharging => ResourceManager.GetString("Overview_BatteryCharging", Culture)!;

    /// <summary>"{0}, plugged in"</summary>
    public static string Overview_BatteryPluggedIn => ResourceManager.GetString("Overview_BatteryPluggedIn", Culture)!;

    /// <summary>"{0}, about {1} left"</summary>
    public static string Overview_BatteryRemaining => ResourceManager.GetString("Overview_BatteryRemaining", Culture)!;

    /// <summary>"Committed memory"</summary>
    public static string Overview_Commit => ResourceManager.GetString("Overview_Commit", Culture)!;

    /// <summary>"{0} of {1}"</summary>
    public static string Overview_CommitOfLimit => ResourceManager.GetString("Overview_CommitOfLimit", Culture)!;

    /// <summary>"CPU"</summary>
    public static string Overview_Cpu => ResourceManager.GetString("Overview_Cpu", Culture)!;

    /// <summary>"CPU usage history" (Accessibility name)</summary>
    public static string Overview_CpuHistory => ResourceManager.GetString("Overview_CpuHistory", Culture)!;

    /// <summary>"{0} dedicated memory in use"</summary>
    public static string Overview_DedicatedMemoryInUse => ResourceManager.GetString("Overview_DedicatedMemoryInUse", Culture)!;

    /// <summary>"Disk"</summary>
    public static string Overview_Disk => ResourceManager.GetString("Overview_Disk", Culture)!;

    /// <summary>"Disk activity history" (Accessibility name)</summary>
    public static string Overview_DiskHistory => ResourceManager.GetString("Overview_DiskHistory", Culture)!;

    /// <summary>"{0} down, {1} up"</summary>
    public static string Overview_DownUp => ResourceManager.GetString("Overview_DownUp", Culture)!;

    /// <summary>"{0} free of {1}"</summary>
    public static string Overview_FreeOfTotal => ResourceManager.GetString("Overview_FreeOfTotal", Culture)!;

    /// <summary>"{0} GHz, {1} processors"</summary>
    public static string Overview_FrequencyAndProcessors => ResourceManager.GetString("Overview_FrequencyAndProcessors", Culture)!;

    /// <summary>"GPU"</summary>
    public static string Overview_Gpu => ResourceManager.GetString("Overview_Gpu", Culture)!;

    /// <summary>"GPU usage history" (Accessibility name)</summary>
    public static string Overview_GpuHistory => ResourceManager.GetString("Overview_GpuHistory", Culture)!;

    /// <summary>"GPU counters are not available on this system."</summary>
    public static string Overview_GpuUnavailable => ResourceManager.GetString("Overview_GpuUnavailable", Culture)!;

    /// <summary>"Memory"</summary>
    public static string Overview_Memory => ResourceManager.GetString("Overview_Memory", Culture)!;

    /// <summary>"Memory usage history" (Accessibility name)</summary>
    public static string Overview_MemoryHistory => ResourceManager.GetString("Overview_MemoryHistory", Culture)!;

    /// <summary>"Network"</summary>
    public static string Overview_Network => ResourceManager.GetString("Overview_Network", Culture)!;

    /// <summary>"Network activity history" (Accessibility name)</summary>
    public static string Overview_NetworkHistory => ResourceManager.GetString("Overview_NetworkHistory", Culture)!;

    /// <summary>"of {0}, {1} available" (Memory caption: of 32 GB, 13.8 GB available)</summary>
    public static string Overview_OfTotalAvailable => ResourceManager.GetString("Overview_OfTotalAvailable", Culture)!;

    /// <summary>"Processes"</summary>
    public static string Overview_Processes => ResourceManager.GetString("Overview_Processes", Culture)!;

    /// <summary>"{0} processes, {1} threads, {2} handles"</summary>
    public static string Overview_ProcessesThreadsHandles => ResourceManager.GetString("Overview_ProcessesThreadsHandles", Culture)!;

    /// <summary>"{0} processors"</summary>
    public static string Overview_Processors => ResourceManager.GetString("Overview_Processors", Culture)!;

    /// <summary>"{0} read, {1} write"</summary>
    public static string Overview_ReadWrite => ResourceManager.GetString("Overview_ReadWrite", Culture)!;

    /// <summary>"Storage"</summary>
    public static string Overview_Storage => ResourceManager.GetString("Overview_Storage", Culture)!;

    /// <summary>"System"</summary>
    public static string Overview_System => ResourceManager.GetString("Overview_System", Culture)!;

    /// <summary>"System drive"</summary>
    public static string Overview_SystemVolume => ResourceManager.GetString("Overview_SystemVolume", Culture)!;

    /// <summary>"Uptime"</summary>
    public static string Overview_Uptime => ResourceManager.GetString("Overview_Uptime", Culture)!;

    /// <summary>"{0} ({1})" (Volume title: Windows (C:))</summary>
    public static string Overview_VolumeLabel => ResourceManager.GetString("Overview_VolumeLabel", Culture)!;

    /// <summary>"Nothing to show yet." (Placeholder while a page has no data.)</summary>
    public static string Page_NothingYet => ResourceManager.GetString("Page_NothingYet", Culture)!;

    /// <summary>"I understand the risk"</summary>
    public static string Processes_Acknowledge => ResourceManager.GetString("Processes_Acknowledge", Culture)!;

    /// <summary>"Access denied. {0} belongs to another account; restart WinClean as administrator to manage it."</summary>
    public static string Processes_ActionAccessDenied => ResourceManager.GetString("Processes_ActionAccessDenied", Culture)!;

    /// <summary>"{0} could not be changed: {1}"</summary>
    public static string Processes_ActionFailed => ResourceManager.GetString("Processes_ActionFailed", Culture)!;

    /// <summary>"{0} had already exited."</summary>
    public static string Processes_ActionGone => ResourceManager.GetString("Processes_ActionGone", Culture)!;

    /// <summary>"{0} of {1} processes could not be ended."</summary>
    public static string Processes_ActionPartial => ResourceManager.GetString("Processes_ActionPartial", Culture)!;

    /// <summary>"CPU"</summary>
    public static string Processes_ColumnCpu => ResourceManager.GetString("Processes_ColumnCpu", Culture)!;

    /// <summary>"GPU"</summary>
    public static string Processes_ColumnGpu => ResourceManager.GetString("Processes_ColumnGpu", Culture)!;

    /// <summary>"I/O"</summary>
    public static string Processes_ColumnIo => ResourceManager.GetString("Processes_ColumnIo", Culture)!;

    /// <summary>"Memory"</summary>
    public static string Processes_ColumnMemory => ResourceManager.GetString("Processes_ColumnMemory", Culture)!;

    /// <summary>"Name"</summary>
    public static string Processes_ColumnName => ResourceManager.GetString("Processes_ColumnName", Culture)!;

    /// <summary>"PID"</summary>
    public static string Processes_ColumnPid => ResourceManager.GetString("Processes_ColumnPid", Culture)!;

    /// <summary>"Status"</summary>
    public static string Processes_ColumnStatus => ResourceManager.GetString("Processes_ColumnStatus", Culture)!;

    /// <summary>"This is a Windows component. Ending it can make Windows unstable or sign you out."</summary>
    public static string Processes_ComponentWarning => ResourceManager.GetString("Processes_ComponentWarning", Culture)!;

    /// <summary>"Details"</summary>
    public static string Processes_Details => ResourceManager.GetString("Processes_Details", Culture)!;

    /// <summary>"End {0} ({1} processes)?"</summary>
    public static string Processes_EndGroupTitle => ResourceManager.GetString("Processes_EndGroupTitle", Culture)!;

    /// <summary>"Unsaved data in these processes will be lost."</summary>
    public static string Processes_EndManyMessage => ResourceManager.GetString("Processes_EndManyMessage", Culture)!;

    /// <summary>"Unsaved data in this process will be lost."</summary>
    public static string Processes_EndMessage => ResourceManager.GetString("Processes_EndMessage", Culture)!;

    /// <summary>"End process"</summary>
    public static string Processes_EndProcess => ResourceManager.GetString("Processes_EndProcess", Culture)!;

    /// <summary>"End process tree"</summary>
    public static string Processes_EndProcessTree => ResourceManager.GetString("Processes_EndProcessTree", Culture)!;

    /// <summary>"End {0} (PID {1})?"</summary>
    public static string Processes_EndTitle => ResourceManager.GetString("Processes_EndTitle", Culture)!;

    /// <summary>"End {0} and the {1} processes it started?"</summary>
    public static string Processes_EndTreeTitle => ResourceManager.GetString("Processes_EndTreeTitle", Culture)!;

    /// <summary>"Group by application"</summary>
    public static string Processes_GroupByApplication => ResourceManager.GetString("Processes_GroupByApplication", Culture)!;

    /// <summary>"Bytes read and written through files, pipes and sockets"</summary>
    public static string Processes_IoTooltip => ResourceManager.GetString("Processes_IoTooltip", Culture)!;

    /// <summary>"{0} processes" (Group row badge)</summary>
    public static string Processes_MemberCount => ResourceManager.GetString("Processes_MemberCount", Culture)!;

    /// <summary>"Private working set, the memory only this process uses"</summary>
    public static string Processes_MemoryTooltip => ResourceManager.GetString("Processes_MemoryTooltip", Culture)!;

    /// <summary>"Select a process to see its details."</summary>
    public static string Processes_NoSelection => ResourceManager.GetString("Processes_NoSelection", Culture)!;

    /// <summary>"Show details pane"</summary>
    public static string Processes_OpenDetails => ResourceManager.GetString("Processes_OpenDetails", Culture)!;

    /// <summary>"Pause updates"</summary>
    public static string Processes_Pause => ResourceManager.GetString("Processes_Pause", Culture)!;

    /// <summary>"Updates paused"</summary>
    public static string Processes_Paused => ResourceManager.GetString("Processes_Paused", Culture)!;

    /// <summary>"Windows marks this process as critical. Ending it would stop Windows."</summary>
    public static string Processes_ProtectedCritical => ResourceManager.GetString("Processes_ProtectedCritical", Culture)!;

    /// <summary>"Protected Windows process. End and suspend are not available because Windows depends on it."</summary>
    public static string Processes_ProtectedKernel => ResourceManager.GetString("Processes_ProtectedKernel", Culture)!;

    /// <summary>"This is WinClean itself. Close the window to end it."</summary>
    public static string Processes_ProtectedSelf => ResourceManager.GetString("Processes_ProtectedSelf", Culture)!;

    /// <summary>"Memory of a virtual machine. Shut the machine down from WSL, Docker Desktop or Hyper-V instead; wsl --shutdown stops WSL."</summary>
    public static string Processes_ProtectedVm => ResourceManager.GetString("Processes_ProtectedVm", Culture)!;

    /// <summary>"Resume"</summary>
    public static string Processes_Resume => ResourceManager.GetString("Processes_Resume", Culture)!;

    /// <summary>"Resume updates"</summary>
    public static string Processes_ResumeUpdates => ResourceManager.GetString("Processes_ResumeUpdates", Culture)!;

    /// <summary>"{0}, {1} memory, {2} CPU" (Screen reader name of a row)</summary>
    public static string Processes_RowAutomation => ResourceManager.GetString("Processes_RowAutomation", Culture)!;

    /// <summary>"Search by name, PID or path"</summary>
    public static string Processes_SearchPlaceholder => ResourceManager.GetString("Processes_SearchPlaceholder", Culture)!;

    /// <summary>"Show system processes"</summary>
    public static string Processes_ShowSystem => ResourceManager.GetString("Processes_ShowSystem", Culture)!;

    /// <summary>"Not responding"</summary>
    public static string Processes_StatusNotResponding => ResourceManager.GetString("Processes_StatusNotResponding", Culture)!;

    /// <summary>"Suspended"</summary>
    public static string Processes_StatusSuspended => ResourceManager.GetString("Processes_StatusSuspended", Culture)!;

    /// <summary>"{0} processes"</summary>
    public static string Processes_Summary => ResourceManager.GetString("Processes_Summary", Culture)!;

    /// <summary>"{0} processes, {1} applications"</summary>
    public static string Processes_SummaryGrouped => ResourceManager.GetString("Processes_SummaryGrouped", Culture)!;

    /// <summary>"Suspend"</summary>
    public static string Processes_Suspend => ResourceManager.GetString("Processes_Suspend", Culture)!;

    /// <summary>"This process runs as a system account. Ending it can stop a Windows service."</summary>
    public static string Processes_SystemAccountWarning => ResourceManager.GetString("Processes_SystemAccountWarning", Culture)!;

    /// <summary>"Expand or collapse" (Accessibility name of the chevron on a group row)</summary>
    public static string Processes_ToggleGroup => ResourceManager.GetString("Processes_ToggleGroup", Culture)!;

    /// <summary>"About"</summary>
    public static string Settings_About => ResourceManager.GetString("Settings_About", Culture)!;

    /// <summary>"Administrator"</summary>
    public static string Settings_Administrator => ResourceManager.GetString("Settings_Administrator", Culture)!;

    /// <summary>"Appearance"</summary>
    public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", Culture)!;

    /// <summary>"Celsius"</summary>
    public static string Settings_Celsius => ResourceManager.GetString("Settings_Celsius", Culture)!;

    /// <summary>"Cleanup"</summary>
    public static string Settings_Cleanup => ResourceManager.GetString("Settings_Cleanup", Culture)!;

    /// <summary>"Confirmation before deleting"</summary>
    public static string Settings_CleanupConfirmation => ResourceManager.GetString("Settings_CleanupConfirmation", Culture)!;

    /// <summary>"Always on. Every cleanup shows the exact files first and asks before deleting."</summary>
    public static string Settings_CleanupConfirmationDescription => ResourceManager.GetString("Settings_CleanupConfirmationDescription", Culture)!;

    /// <summary>"Keep running when the window is closed"</summary>
    public static string Settings_CloseToTray => ResourceManager.GetString("Settings_CloseToTray", Culture)!;

    /// <summary>"Closing the window hides it; Exit in the icon&apos;s menu ends WinClean."</summary>
    public static string Settings_CloseToTrayDescription => ResourceManager.GetString("Settings_CloseToTrayDescription", Culture)!;

    /// <summary>"Data"</summary>
    public static string Settings_Data => ResourceManager.GetString("Settings_Data", Culture)!;

    /// <summary>"Data folder"</summary>
    public static string Settings_DataFolder => ResourceManager.GetString("Settings_DataFolder", Culture)!;

    /// <summary>"Settings and logs for this account. Put a file named &quot;portable&quot; next to WinClean.exe to keep them beside the executable instead."</summary>
    public static string Settings_DataFolderPerUser => ResourceManager.GetString("Settings_DataFolderPerUser", Culture)!;

    /// <summary>"Portable mode: settings and logs live next to the executable because a file named &quot;portable&quot; sits beside it."</summary>
    public static string Settings_DataFolderPortable => ResourceManager.GetString("Settings_DataFolderPortable", Culture)!;

    /// <summary>"180 days"</summary>
    public static string Settings_Days180 => ResourceManager.GetString("Settings_Days180", Culture)!;

    /// <summary>"30 days"</summary>
    public static string Settings_Days30 => ResourceManager.GetString("Settings_Days30", Culture)!;

    /// <summary>"1 year"</summary>
    public static string Settings_Days365 => ResourceManager.GetString("Settings_Days365", Culture)!;

    /// <summary>"60 days"</summary>
    public static string Settings_Days60 => ResourceManager.GetString("Settings_Days60", Culture)!;

    /// <summary>"90 days"</summary>
    public static string Settings_Days90 => ResourceManager.GetString("Settings_Days90", Culture)!;

    /// <summary>"OK"</summary>
    public static string Settings_DiagnosticOk => ResourceManager.GetString("Settings_DiagnosticOk", Culture)!;

    /// <summary>"Diagnostics"</summary>
    public static string Settings_Diagnostics => ResourceManager.GetString("Settings_Diagnostics", Culture)!;

    /// <summary>"What each reader reported on this machine. The same list is written by WinClean.exe --self-check."</summary>
    public static string Settings_DiagnosticsDescription => ResourceManager.GetString("Settings_DiagnosticsDescription", Culture)!;

    /// <summary>"WinClean is running as administrator."</summary>
    public static string Settings_Elevated => ResourceManager.GetString("Settings_Elevated", Culture)!;

    /// <summary>"Fahrenheit"</summary>
    public static string Settings_Fahrenheit => ResourceManager.GetString("Settings_Fahrenheit", Culture)!;

    /// <summary>"Group processes by application"</summary>
    public static string Settings_GroupByApplication => ResourceManager.GetString("Settings_GroupByApplication", Culture)!;

    /// <summary>"The default for the Processes page; the toggle on the page changes it for the session."</summary>
    public static string Settings_GroupByApplicationDescription => ResourceManager.GetString("Settings_GroupByApplicationDescription", Culture)!;

    /// <summary>"1 hour"</summary>
    public static string Settings_Hours1 => ResourceManager.GetString("Settings_Hours1", Culture)!;

    /// <summary>"24 hours"</summary>
    public static string Settings_Hours24 => ResourceManager.GetString("Settings_Hours24", Culture)!;

    /// <summary>"48 hours"</summary>
    public static string Settings_Hours48 => ResourceManager.GetString("Settings_Hours48", Culture)!;

    /// <summary>"6 hours"</summary>
    public static string Settings_Hours6 => ResourceManager.GetString("Settings_Hours6", Culture)!;

    /// <summary>"Open source under the MIT license."</summary>
    public static string Settings_License => ResourceManager.GetString("Settings_License", Culture)!;

    /// <summary>"Logging"</summary>
    public static string Settings_Logging => ResourceManager.GetString("Settings_Logging", Culture)!;

    /// <summary>"Monitoring"</summary>
    public static string Settings_Monitoring => ResourceManager.GetString("Settings_Monitoring", Culture)!;

    /// <summary>"WinClean is running with standard rights. Administrator rights are needed for Windows temporary files, the Windows Update cache, processes of other accounts and CPU sensors."</summary>
    public static string Settings_NotElevated => ResourceManager.GetString("Settings_NotElevated", Culture)!;

    /// <summary>"Offer installers in Downloads after"</summary>
    public static string Settings_OldDownloadDays => ResourceManager.GetString("Settings_OldDownloadDays", Culture)!;

    /// <summary>"Open data folder"</summary>
    public static string Settings_OpenDataFolder => ResourceManager.GetString("Settings_OpenDataFolder", Culture)!;

    /// <summary>"Open log folder"</summary>
    public static string Settings_OpenLogFolder => ResourceManager.GetString("Settings_OpenLogFolder", Culture)!;

    /// <summary>"Releases"</summary>
    public static string Settings_OpenReleases => ResourceManager.GetString("Settings_OpenReleases", Culture)!;

    /// <summary>"Source code"</summary>
    public static string Settings_OpenRepository => ResourceManager.GetString("Settings_OpenRepository", Culture)!;

    /// <summary>"No account, no telemetry, no analytics, no crash upload and no update check. WinClean never opens a network connection on its own; links and the Windows Update check only run when you click them."</summary>
    public static string Settings_Privacy => ResourceManager.GetString("Settings_Privacy", Culture)!;

    /// <summary>"Refresh interval"</summary>
    public static string Settings_RefreshInterval => ResourceManager.GetString("Settings_RefreshInterval", Culture)!;

    /// <summary>"How often the Overview and Processes pages are updated while they are visible."</summary>
    public static string Settings_RefreshIntervalDescription => ResourceManager.GetString("Settings_RefreshIntervalDescription", Culture)!;

    /// <summary>"Restart as administrator"</summary>
    public static string Settings_RestartAsAdministrator => ResourceManager.GetString("Settings_RestartAsAdministrator", Culture)!;

    /// <summary>"1 second"</summary>
    public static string Settings_Seconds1 => ResourceManager.GetString("Settings_Seconds1", Culture)!;

    /// <summary>"2 seconds"</summary>
    public static string Settings_Seconds2 => ResourceManager.GetString("Settings_Seconds2", Culture)!;

    /// <summary>"5 seconds"</summary>
    public static string Settings_Seconds5 => ResourceManager.GetString("Settings_Seconds5", Culture)!;

    /// <summary>"Hardware sensors"</summary>
    public static string Settings_Sensors => ResourceManager.GetString("Settings_Sensors", Culture)!;

    /// <summary>"Reads CPU, motherboard, GPU and drive temperatures. CPU and motherboard sensors need the PawnIO driver from pawnio.eu and administrator rights; WinClean installs neither."</summary>
    public static string Settings_SensorsDescription => ResourceManager.GetString("Settings_SensorsDescription", Culture)!;

    /// <summary>"Show system processes"</summary>
    public static string Settings_ShowSystemProcesses => ResourceManager.GetString("Settings_ShowSystemProcesses", Culture)!;

    /// <summary>"Windows services and system processes are listed with everything else."</summary>
    public static string Settings_ShowSystemProcessesDescription => ResourceManager.GetString("Settings_ShowSystemProcessesDescription", Culture)!;

    /// <summary>"Consider developer folders stale after"</summary>
    public static string Settings_StaleDays => ResourceManager.GetString("Settings_StaleDays", Culture)!;

    /// <summary>"node_modules, build output and virtual environments in projects untouched for this long are offered for cleanup."</summary>
    public static string Settings_StaleDaysDescription => ResourceManager.GetString("Settings_StaleDaysDescription", Culture)!;

    /// <summary>"Start minimized"</summary>
    public static string Settings_StartMinimized => ResourceManager.GetString("Settings_StartMinimized", Culture)!;

    /// <summary>"Only the notification area icon appears at sign-in. Needs the icon to be enabled."</summary>
    public static string Settings_StartMinimizedDescription => ResourceManager.GetString("Settings_StartMinimizedDescription", Culture)!;

    /// <summary>"Start with Windows"</summary>
    public static string Settings_StartWithWindows => ResourceManager.GetString("Settings_StartWithWindows", Culture)!;

    /// <summary>"Adds WinClean to the Run key of your account; no service and no scheduled task."</summary>
    public static string Settings_StartWithWindowsDescription => ResourceManager.GetString("Settings_StartWithWindowsDescription", Culture)!;

    /// <summary>"Startup"</summary>
    public static string Settings_Startup => ResourceManager.GetString("Settings_Startup", Culture)!;

    /// <summary>"Temperature unit"</summary>
    public static string Settings_TemperatureUnit => ResourceManager.GetString("Settings_TemperatureUnit", Culture)!;

    /// <summary>"Leave temporary files alone for"</summary>
    public static string Settings_TemporaryAge => ResourceManager.GetString("Settings_TemporaryAge", Culture)!;

    /// <summary>"Files younger than this stay, so a running installer or build is never disturbed."</summary>
    public static string Settings_TemporaryAgeDescription => ResourceManager.GetString("Settings_TemporaryAgeDescription", Culture)!;

    /// <summary>"Theme"</summary>
    public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", Culture)!;

    /// <summary>"Dark"</summary>
    public static string Settings_ThemeDark => ResourceManager.GetString("Settings_ThemeDark", Culture)!;

    /// <summary>"Light"</summary>
    public static string Settings_ThemeLight => ResourceManager.GetString("Settings_ThemeLight", Culture)!;

    /// <summary>"Follow Windows"</summary>
    public static string Settings_ThemeSystem => ResourceManager.GetString("Settings_ThemeSystem", Culture)!;

    /// <summary>"Notification area"</summary>
    public static string Settings_Tray => ResourceManager.GetString("Settings_Tray", Culture)!;

    /// <summary>"CPU"</summary>
    public static string Settings_TrayCpu => ResourceManager.GetString("Settings_TrayCpu", Culture)!;

    /// <summary>"System drive"</summary>
    public static string Settings_TrayDisk => ResourceManager.GetString("Settings_TrayDisk", Culture)!;

    /// <summary>"Show an icon in the notification area"</summary>
    public static string Settings_TrayEnabled => ResourceManager.GetString("Settings_TrayEnabled", Culture)!;

    /// <summary>"The icon shows live usage and opens WinClean with a click. Sampling continues in the background at a slower pace."</summary>
    public static string Settings_TrayEnabledDescription => ResourceManager.GetString("Settings_TrayEnabledDescription", Culture)!;

    /// <summary>"Memory"</summary>
    public static string Settings_TrayMemory => ResourceManager.GetString("Settings_TrayMemory", Culture)!;

    /// <summary>"Metrics"</summary>
    public static string Settings_TrayMetrics => ResourceManager.GetString("Settings_TrayMetrics", Culture)!;

    /// <summary>"Icon style"</summary>
    public static string Settings_TrayStyle => ResourceManager.GetString("Settings_TrayStyle", Culture)!;

    /// <summary>"Bars"</summary>
    public static string Settings_TrayStyleBars => ResourceManager.GetString("Settings_TrayStyleBars", Culture)!;

    /// <summary>"Numbers"</summary>
    public static string Settings_TrayStyleNumber => ResourceManager.GetString("Settings_TrayStyleNumber", Culture)!;

    /// <summary>"Verbose logging"</summary>
    public static string Settings_VerboseLogging => ResourceManager.GetString("Settings_VerboseLogging", Culture)!;

    /// <summary>"Writes debug detail to the log files. Useful when reporting a problem."</summary>
    public static string Settings_VerboseLoggingDescription => ResourceManager.GetString("Settings_VerboseLoggingDescription", Culture)!;

    /// <summary>"{0} {1}" (Name and version)</summary>
    public static string Settings_VersionLine => ResourceManager.GetString("Settings_VersionLine", Culture)!;

    /// <summary>"WinClean is using {0} of memory."</summary>
    public static string Settings_WorkingSet => ResourceManager.GetString("Settings_WorkingSet", Culture)!;

    /// <summary>"CPU {0}"</summary>
    public static string Tray_CpuTip => ResourceManager.GetString("Tray_CpuTip", Culture)!;

    /// <summary>"{0} {1} free of {2}"</summary>
    public static string Tray_DiskTip => ResourceManager.GetString("Tray_DiskTip", Culture)!;

    /// <summary>"Exit"</summary>
    public static string Tray_Exit => ResourceManager.GetString("Tray_Exit", Culture)!;

    /// <summary>"Memory {0} of {1} ({2})"</summary>
    public static string Tray_MemoryTip => ResourceManager.GetString("Tray_MemoryTip", Culture)!;

    /// <summary>"Open WinClean"</summary>
    public static string Tray_Open => ResourceManager.GetString("Tray_Open", Culture)!;
}
