#:property RestorePackagesWithLockFile=false

// Regenerates src/WinClean/Resources/Strings.Designer.cs from Strings.resx.
//
//   dotnet run eng/UpdateStrings.cs            rewrite the file
//   dotnet run eng/UpdateStrings.cs -- --check fail when the committed file is stale (used by CI)

using System.Text;
using System.Xml.Linq;

var root = FindRepositoryRoot();
var resxPath = Path.Combine(root, "src", "WinClean", "Resources", "Strings.resx");
var outputPath = Path.Combine(root, "src", "WinClean", "Resources", "Strings.Designer.cs");

var entries = XDocument.Load(resxPath).Root!
    .Elements("data")
    .Select(data => new Entry(
        (string)data.Attribute("name")!,
        (string?)data.Element("value") ?? string.Empty,
        (string?)data.Element("comment")))
    .OrderBy(entry => entry.Name, StringComparer.Ordinal)
    .ToList();

var generated = Generate(entries);

if (args.Contains("--check"))
{
    var current = File.Exists(outputPath) ? File.ReadAllText(outputPath) : string.Empty;

    if (!string.Equals(Normalize(current), Normalize(generated), StringComparison.Ordinal))
    {
        Console.Error.WriteLine("Strings.Designer.cs is out of date. Run: dotnet run eng/UpdateStrings.cs");
        return 1;
    }

    Console.WriteLine("Strings.Designer.cs is up to date.");
    return 0;
}

File.WriteAllText(outputPath, generated, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {entries.Count} strings to {Path.GetRelativePath(root, outputPath)}");
return 0;

static string Generate(List<Entry> entries)
{
    var builder = new StringBuilder();

    builder.Append("""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Generated from Strings.resx by eng/UpdateStrings.cs. Do not edit by hand:
        //     change the resx and run "dotnet run eng/UpdateStrings.cs".
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        namespace WinClean.Resources;

        using System.Globalization;
        using System.Resources;

        [System.CodeDom.Compiler.GeneratedCode("eng/UpdateStrings.cs", "1.0")]
        [System.Diagnostics.DebuggerNonUserCode]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public static class Strings
        {
            private static ResourceManager? resourceManager;

            public static ResourceManager ResourceManager =>
                resourceManager ??= new ResourceManager("WinClean.Resources.Strings", typeof(Strings).Assembly);

            public static CultureInfo? Culture { get; set; }

        """);

    foreach (var entry in entries)
    {
        builder.AppendLine();
        builder.Append("    /// <summary>").Append(Summary(entry)).AppendLine("</summary>");
        builder.Append("    public static string ").Append(entry.Name)
            .Append(" => ResourceManager.GetString(\"").Append(entry.Name).AppendLine("\", Culture)!;");
    }

    builder.AppendLine("}");
    return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
}

static string Summary(Entry entry)
{
    var text = entry.Value.Replace("\r", string.Empty, StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
    var escaped = System.Security.SecurityElement.Escape(text) ?? string.Empty;
    return entry.Comment is { Length: > 0 } comment
        ? $"\"{escaped}\" ({System.Security.SecurityElement.Escape(comment)})"
        : $"\"{escaped}\"";
}

static string Normalize(string text) => text.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd();

static string FindRepositoryRoot()
{
    var directory = new DirectoryInfo(AppContext.BaseDirectory);

    for (var candidate = new DirectoryInfo(Environment.CurrentDirectory); candidate is not null; candidate = candidate.Parent)
    {
        if (File.Exists(Path.Combine(candidate.FullName, "WinClean.slnx")))
        {
            return candidate.FullName;
        }
    }

    throw new InvalidOperationException($"Run this from inside the repository (started in {directory.FullName}).");
}

internal sealed record Entry(string Name, string Value, string? Comment);
